apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.redis.name }}
  namespace: {{ .Values.namespace }}
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    maxmemory 6gb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    port {{ .Values.env.config.REDIS_PORT }}
