apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.stack.name }}
  namespace: {{ .Values.namespace }}
data:
  DOMAIN: "{{ .Values.env.config.DOMAIN }}"
  ENVIRONMENT: "{{ .Values.env.config.ENVIRONMENT }}"
  FRONTEND_PORT: "{{ .Values.env.config.FRONTEND_PORT }}"
  BACKEND_PORT: "{{ .Values.env.config.BACKEND_PORT }}"
  PROJECT_NAME: "{{ .Values.env.config.PROJECT_NAME }}"
  STACK_NAME: "{{ .Values.env.config.STACK_NAME }}"
  REDIS_PORT: "{{ .Values.env.config.REDIS_PORT }}"
  BACKEND_CORS_ORIGINS: "{{ .Values.env.config.BACKEND_CORS_ORIGINS }}"
  MINIO_ENDPOINT: "{{ .Values.env.config.MINIO_ENDPOINT }}"
  MINIO_HOST: "{{ .Values.env.config.MINIO_HOST }}"
  MINIO_PORT: "{{ .Values.env.config.MINIO_PORT }}"
  MINIO_SECURE: "{{ .Values.env.config.MINIO_SECURE }}"
  NOMINATIM_PORT: "{{ .Values.nominatim.service.port }}"
  NOMINATIM_DOMAIN: "nominatim"

